builds:
  - binary: percentile
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: kazeburo
    name: percentile
brews:
  - description: "display percentile"
    tap:
      owner: kazeburo
      name: homebrew-tap
    homepage: "https://github.com/kazeburo/percentile"
    install: |
      bin.install "percentile"
